// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7xlTS5a-gbeAxBbk8SflExJVCAEbUbiA',
    appId: '1:218278572309:web:67a4c2bbf8379d6df4b91c',
    messagingSenderId: '218278572309',
    projectId: 'pk-fcm-7c2db',
    authDomain: 'pk-fcm-7c2db.firebaseapp.com',
    storageBucket: 'pk-fcm-7c2db.firebasestorage.app',
    measurementId: 'G-7G4D11VEEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqmL5bJT-fzGTx9V5RU4lLfNgaNb8PK5E',
    appId: '1:218278572309:android:029b3a9ba628d993f4b91c',
    messagingSenderId: '218278572309',
    projectId: 'pk-fcm-7c2db',
    storageBucket: 'pk-fcm-7c2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGgkG5K8w9RUHJFzQt1w9Hw-Sd0oZjR_s',
    appId: '1:218278572309:ios:2f8d1bfec931d991f4b91c',
    messagingSenderId: '218278572309',
    projectId: 'pk-fcm-7c2db',
    storageBucket: 'pk-fcm-7c2db.firebasestorage.app',
    iosBundleId: 'com.example.firebaseattempt1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGgkG5K8w9RUHJFzQt1w9Hw-Sd0oZjR_s',
    appId: '1:218278572309:ios:2f8d1bfec931d991f4b91c',
    messagingSenderId: '218278572309',
    projectId: 'pk-fcm-7c2db',
    storageBucket: 'pk-fcm-7c2db.firebasestorage.app',
    iosBundleId: 'com.example.firebaseattempt1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7xlTS5a-gbeAxBbk8SflExJVCAEbUbiA',
    appId: '1:218278572309:web:70c822a8c8280a8ff4b91c',
    messagingSenderId: '218278572309',
    projectId: 'pk-fcm-7c2db',
    authDomain: 'pk-fcm-7c2db.firebaseapp.com',
    storageBucket: 'pk-fcm-7c2db.firebasestorage.app',
    measurementId: 'G-QCX54WCND8',
  );
}
